spring:
  datasource:
    url: jdbc:postgresql://10.30.120.24:5432/scashworkflow
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  # Uncomment to use PostgreSQL instead of in-memory database
  # jpa:
  #   database-platform: org.hibernate.dialect.PostgreSQLDialect

workflow:
  bpmn-path: src/main/resources/processes/hello-user.bpmn20.xml
