spring:
  # Uncomment the following lines and run `docker compose up -d db` to enable
  # PostgreSQL persistence. Without this the application uses an in-memory
  # database.
  # datasource:
  #   url: jdbc:postgresql://localhost:5432/activiti
  #   username: activiti
  #   password: activiti
  #   driver-class-name: org.postgresql.Driver
  # jpa:
  #   database-platform: org.hibernate.dialect.PostgreSQLDialect

